version: '1'

services:
  web:
    type: web
    build: .
    ports:
      80:5000
    volumes:
      - data:/app/data

jobs:  # ← КРИТИЧЕСКИ ВАЖНО: раздел должен называться JOBS
  parser:
    type: cron  # ← Должно быть "cron" вместо "job"
    schedule: "0 5-14 * * *"
    build: .
    command: ["python", "parser.py"]  # ← "command" вместо "commands"
    volumes:
      - data:/app/data

volumes:
  data:
    name: currency-data
    size: 1GB