version: '1'

services:
  web:
    type: web
    build: .
    ports:
      80:5000
    volumes:
      - data:/app/data

jobs:  # <-- ДОЛЖЕН БЫТЬ РАЗДЕЛ jobs, НЕ services!
  parser:
    type: cron  # <-- Ключевое исправление: type должен быть "cron"
    schedule: "0 5-14 * * *"
    build: .
    command: ["python", "parser.py"]  # <-- Используйте "command" вместо "commands"
    volumes:
      - data:/app/data

volumes:
  data:
    name: currency-data
    size: 1GB