version: '1'

services:
  web:
    type: web
    build:
      context: .
    ports:
      80: 5000
    volumes:
      - name: currency-data
        mount: /app/data

jobs:
  parser:
    type: cron
    schedule: "0 5-14 * * *"  # каждый час с 5 до 14
    build:
      context: .
    command: ["python", "parser.py"]
    volumes:
      - name: currency-data
        mount: /app/data

volumes:
  currency-data:
    size: 1GB