version: "1.0"

project:
  name: currency-app

volumes:
  - name: currency-data
    type: ssd  # явно указываем тип хранилища
    size: 1GB

services:
  - name: web
    containers:
      - ports:
          - 80:5000  # внешний:внутренний порт
        build:
          context: .
        volumes:
          - name: currency-data
            mountPath: /app/data  # правильный синтаксис

jobs:
  - name: parser
    type: cron
    schedule: "0 5-14 * * *"  # каждый час с 5 до 14 по UTC
    containers:
      - build:
          context: .
        command: ["python", "parser.py"]
        volumes:
          - name: currency-data
            mountPath: /app/data  # идентичный путь!