version: '1'

services:
  web:
    type: web
    build: .
    ports:
      80:5000
    volumes:
      - data:/app/data

jobs:
  parser:
    type: cron
    schedule: "0 5-14 * * *"
    build: .
    command: ["python", "parser.py"]
    volumes:
      - data:/app/data

volumes:
  data:
    name: currency-data
    size: 1GB
